POST http://localhost:3000/cinemas
content-type: application/json

{
    "name": "Grand Cinema",
    "numberPlace": 250,
    "currentTime": 120,
    "createdDate": "2024-12-22",
    "numberPerson": 5,
    "organization": "Cinema Group"
}

###
POST http://localhost:3000/events
content-type: application/json

{
    "name": "Tech Conference",
    "genre": "Education",
    "time": 240,
    "date": "2024-11-15",
    "numberPerson": 300
}

###
POST http://localhost:3000/events
content-type: application/json

{
    "name": "Concert Night",
    "genre": "Music",
    "time": 180,
    "date": "2024-12-31",
    "numberPerson": 500
}


###
POST http://localhost:3000/reviews
Content-Type: application/json

{
    "contenu": "Excellente performance des acteurs, mais le scénario était prévisible.",
    "rating": 4,
    "film_id": 1,
    "user_id": 2
}

###
POST http://localhost:3000/reviews
Content-Type: application/json

{
    "contenu": "j'ai adoré le film , dommage qu'il ne soit pas plus long.",
    "rating": 5,
    "film_id": 1,
    "user_id": 2
}

### user ...