services:
  server:
    image: node:alpine
    working_dir: /app
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: mysql://root:pass@db:3306/cinema
      JWT_SECRET: secret
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: cinema
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: {}